Ticket8210 add ioc lndyisw
ISISComputingGroup/EPICS-Lndyisw pull request #1
Opened 2024-03-25 20:02 UTC by Chsudeepta

IOC created for LYNDY ISwitch device

2024-04-02 12:26 UTC, LowriJenkins requested changes
is it not possible to test this ioc at all? if so you need to remove the test_that_fails, as it will cause system tests to fail, it looks like none of the test folder is used, might not be nesecary?
Otherwise looks good!

2024-04-02 12:48 UTC, Chsudeepta commented
@LowriJenkins . right now we don't have any simulator for the SNMP. I am trying to implement a simulator for SNMP (Freddie has pointed to a library). Once it is found to be working, I intend to update the IOC framework with the test cases for this new IOC

2024-04-02 12:51 UTC, LowriJenkins commented
hmm, should this go out of review for now then? or will that be accomplished as a seperate ticket? if yes, we should still remove that `test_that_fails` or else it will cause system tests to fail until you implement the simulator.

2024-04-02 12:56 UTC, Chsudeepta commented
Ok. Then may be we should move it out of review for the time being and see whether the simulator can be implemented.

2024-04-10 13:14 UTC, LowriJenkins commented
for your tests here, is there any additional setup beyond the normal nessecary of just running run_tests.bat after having made the nessecary files (and in this case the genie python changes)?

2024-04-10 13:39 UTC, Chsudeepta commented
No. I think you should be able to run the tests after the IOC has been made in the usual manner.

2024-04-11 10:41 UTC, LowriJenkins requested changes
Just some minor changes due to it not using a standard emulator, otherwise looks good

2024-04-11 10:41 UTC, LowriJenkins commented on system_tests/tests/lndyisw.py
> +TEST_MODES = [TestModes.RECSIM, TestModes.DEVSIM]
I don't think there is any point running in RECSIM since you don't have any simulation records, so can probably just test in DEVSIM

2024-04-11 10:41 UTC, LowriJenkins commented on system_tests/lewis_emulators/lewis_versions.py
> +LEWIS_1_3_0 = "1.3.0"
Can delete this whole folder since we're not using a lewis emulator having this here is just confusing

2024-04-11 11:03 UTC, Chsudeepta commented on system_tests/lewis_emulators/lewis_versions.py
> +LEWIS_1_3_0 = "1.3.0"
This was auto-generated. If the standard practice is to remove then I will go ahead and delete

2024-04-11 11:17 UTC, Chsudeepta commented on system_tests/tests/lndyisw.py
> +TEST_MODES = [TestModes.RECSIM, TestModes.DEVSIM]
Yes, you are right. We can do away with RECSIM

2024-04-11 11:31 UTC, LowriJenkins commented on system_tests/lewis_emulators/lewis_versions.py
> +LEWIS_1_3_0 = "1.3.0"
I think it might end up being confusing in future if people attempt to emulate this device with an emulator that does nothing, normally an emulator would be set up, but as in this case we are using your simulator instead, it doesn't make sense to keep this

2024-04-11 11:58 UTC, LowriJenkins commented on system_tests/lewis_emulators/lewis_versions.py
> +LEWIS_1_3_0 = "1.3.0"
Given how rarely we use non-lewis emulators Im not sure we actually have standard practise for this scenario

2024-04-11 12:19 UTC, Chsudeepta commented on system_tests/lewis_emulators/lewis_versions.py
> +LEWIS_1_3_0 = "1.3.0"
Ok. Deleting the folder then.

2024-04-11 12:33 UTC, LowriJenkins approved these changes

2024-04-11 12:36 UTC, merged